default['dataloop_chef_handler']['host']      = 'app.dataloop.io'
default['dataloop_chef_handler']['api_token'] = ''
default['dataloop_chef_handler']['org']       = ''
default['dataloop_chef_handler']['account']   = 'default'
default['dataloop_chef_handler']['stream']    = 'chef'
